package com.fertigApp.backend.controller;

import com.fertigApp.backend.model.Usuario;
import com.fertigApp.backend.repository.UsuarioRepository;
import com.fertigApp.backend.requestModels.RequestUsuario;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController	// This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class UsuarioController {
	@Autowired // This means to get the bean called usuarioRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UsuarioRepository usuarioRepository;

	@Autowired
	private PasswordEncoder passwordEncoder;

	@GetMapping(path="/users")
	public @ResponseBody Iterable<Usuario> getAllUsuarios() {
		return usuarioRepository.findAll();
	}

	@GetMapping(path="/users/get/{user}")
	public Usuario getUsuario(@PathVariable String user) {
		try {
			return usuarioRepository.findById(user).get();
		} catch(java.util.NoSuchElementException ex){
			return null;
		}
	}

	@PutMapping(path="/users/update/{correo}")
	public Usuario replaceUsuario(@PathVariable String correo, @RequestBody RequestUsuario requestUsuario) {
		Usuario user = new Usuario();
		user.setCorreo(requestUsuario.getCorreo());
		user.setNombre(requestUsuario.getNombre());
		user.setUsuario(requestUsuario.getUsuario());
		user.setPassword(passwordEncoder.encode(requestUsuario.getPassword()));
		return usuarioRepository.findById(correo)
				.map(usuario -> {
					usuario.setCorreo(user.getCorreo());
					usuario.setNombre(user.getNombre());
					usuario.setPassword(user.getPassword());
					usuarioRepository.save(usuario);
					return usuario;
				})
				.orElseGet(() -> {
					Usuario newUser = new Usuario();
					newUser.setCorreo(user.getCorreo());
					newUser.setNombre(user.getNombre());
					newUser.setPassword(user.getPassword());
					usuarioRepository.save(newUser);
					return newUser;
				});
	}

	@PostMapping(path="/users/addUser") // Map ONLY POST Requests
	public @ResponseBody ResponseEntity<Void> addNewUsuario (@RequestBody RequestUsuario requestUsuario) {
		Usuario usuario = new Usuario();
		usuario.setCorreo(requestUsuario.getCorreo());
		usuario.setNombre(requestUsuario.getNombre());
		usuario.setUsuario(requestUsuario.getUsuario());
		usuario.setPassword(passwordEncoder.encode(requestUsuario.getPassword()));

		if (usuarioRepository.existsById(usuario.getUsuario()))
			return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
		List<Usuario> usuarios = (List<Usuario>) usuarioRepository.findByCorreo(usuario.getCorreo());
		if(!usuarios.isEmpty())
			return new ResponseEntity<>(HttpStatus.CONFLICT);
		usuarioRepository.save(usuario);
		return new ResponseEntity<>(HttpStatus.CREATED);
	}

	@DeleteMapping(path="/users/delete/{user}")
	public boolean deleteUsuario(@PathVariable String user) {
		try{
			usuarioRepository.deleteById(user);
			return true;
		} catch(org.springframework.dao.EmptyResultDataAccessException ex){
			return false;
		}
	}

	@RequestMapping("/publica")
	public String publico() {
		return "Pagina Publica";
	}
	@RequestMapping("/privada")
	public String privada() {
		return "Pagina Privada";
	}
	@RequestMapping("/admin")
	public String admin() {
		return "Pagina Administrador";
	}/**/
}
